FROM node:20-alpine


WORKDIR /app

# Copy only package files first (better caching)
COPY package*.json ./

RUN npm install

# Then copy the rest
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host"]


