ALTER SESSION SET CONTAINER = XEPDB!;
ALTER SESSION SET CURRENT_SCHEMA = APP;
CREATE TABLE unoptimized(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Severity INT,
    State VARCHAR(2),
    Precipitation FLOAT, 
    Windy SMALLINT, 
    Start_Lng NUMERIC, 
    Start_Lat NUMERIC, 
    Start_time DATE, 
    End_time DATE
);

CREATE TABLE optimized(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Severity INT,
    State VARCHAR(2),
    Precipitation FLOAT, 
    Windy SMALLINT, 
    Start_Lng NUMERIC, 
    Start_Lat NUMERIC, 
    Start_time DATE, 
    End_time DATE
);

ALTER TABLE UNOPTIMIZED NOLOGGING;
ALTER TABLE OPTIMIZED NOLOGGING;
