

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APP;

CREATE TABLE unoptimized(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Severity INT,
    State VARCHAR(2),
    Precipitation FLOAT, 
    Windy NUMBER, 
    Start_Lng NUMERIC, 
    Start_Lat NUMERIC, 
    "Time" DATE, 
    "Date" DATE
);

CREATE TABLE optimized(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Severity INT,
    State VARCHAR(2),
    Precipitation FLOAT, 
    Windy NUMBER, 
    Start_Lng NUMERIC, 
    Start_Lat NUMERIC, 
    "Time" DATE, 
    "Date" DATE
);

CREATE INDEX Precipitation_idx on optimized(Precipitation);
CREATE INDEX Windy_idx on optimized(Windy);

ALTER TABLE UNOPTIMIZED NOLOGGING;
ALTER TABLE OPTIMIZED NOLOGGING;
