CREATE TABLE IF NOT EXISTS unoptimized(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Severity INT,
    State VARCHAR(2),
    Precipitation FLOAT, 
    Windy SMALLINT, 
    Start_Lng LONG, 
    Start_Lat LONG, 
    Start_time DATE, 
    End_time DATE
)

CREATE TABLE IF NOT EXISTS optimized(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Severity INT,
    State VARCHAR(2),
    Precipitation FLOAT, 
    Windy SMALLINT, 
    Start_Lng LONG, 
    Start_Lat LONG, 
    Start_time DATE, 
    End_time DATE
)