CREATE TABLE unoptimized(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    severity INT,
    us_state VARCHAR(2),
    precipitation INT, 
    windy SMALLINT, 
    longitude LONG, 
    latitude LONG, 
    start_time DATE, 
    end_time DATE
)

CREATE TABLE optimized(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    severity INT,
    us_state VARCHAR(2),
    precipitation INT, 
    windy SMALLINT, 
    longitude LONG, 
    latitude LONG, 
    start_time DATE, 
    end_time DATE
)